### ISSUE TITLE
Leaf Beds Suggestion: BoP and Azalea wood set support

### ISSUE THREAD

**Issue by vico93** [boyonk913/smoke-signals#2]
First of all, sorry for opening this suggestion ticket here in this repository! Didn't find the Leaf Beds repo on your profile.

Well, basically, have support for both [Biomes o Plenty](https://modrinth.com/mod/biomes-o-plenty) and [Azalea Wood Set](https://modrinth.com/mod/azalea-wood-set) for Leaf Beds, allowing the player to craft using those logs and leaves.

**Comment by boyonk913** [comment]
Hi! Not all my projects have a public repository, sorry about that. I'm still debating what the best way to go about that is, possibly contact me personally or go through CurseForge? Anyway, I have added support for Biomes o' Plenty (I am still looking into Azalea Wood Set) starting from version 1.1 for 1.20.6. I will close this issue as it isn't related to Smoke Signals.

**Comment by vico93** [comment]
> Hi! Not all my projects have a public repository, sorry about that. I'm still debating what the best way to go about that is, possibly contact me personally or go through CurseForge? Anyway, I have added support for Biomes o' Plenty (I am still looking into Azalea Wood Set) starting from version 1.1 for 1.20.6. I will close this issue as it isn't related to Smoke Signals.

Sorry the long delay. Did you have Discord? My username on there is `@vico13`.

About the Azalea Wood Set, [here](https://github.com/Fire-Horse27/azalea-wood/)'s the Github repository. It's made by @Fire-Horse27, if you need to talk with him too about the update.
